# Site settings
title: My Documentation Site
description: A site using the Just the Docs Jekyll theme
baseurl: "" # the subpath of your site, e.g. /docs if hosted at example.com/docs
url: "https://shivapuranik.github.io" # your site's URL

# Build settings
theme: "null"

# Enable search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true

# Navigation
# Order sidebar navigation manually
nav_order: 1
aux_links:
  "View on GitHub":
    - "//github.com/shivapuranik/shivapuranik.github.io"

# Color scheme
color_scheme: light # or dark

# Footer settings
footer_content: "Copyright &copy; 2025 Your Name"

# Optional: Custom logo
logo: "/assets/images/logo.png"

# Markdown processing
markdown: kramdown
highlighter: rouge

# Plugins (allowed on GitHub Pages)
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Exclude from processing
exclude:
  - README.md
  - node_modules/
  - Gemfile
  - Gemfile.lock
