title: My Documentation Site
description: A clean, searchable documentation site powered by Just the Docs
theme: just-the-docs

# Enable search
search_enabled: true

# Base URL — leave blank if deploying to user.github.io
# If your site is at https://username.github.io/repo-name, set baseurl: /repo-name
baseurl: "" 
url: "https://shivapuranik.github.io/"

# Color scheme (light, dark, or nil for default)
color_scheme: light

# Logo settings (optional)
# logo: "/assets/images/logo.png"

# Navigation structure
# If you use a _pages or _docs folder, Just the Docs will build nav automatically.
# You can also define explicit order like this:
nav_order: 1
nav_external_links:
  - title: GitHub Repository
    url: https://github.com/shivapuranik/shivapuranik.github.io

# Footer content (optional)
footer_content: "Copyright &copy; 2025 Your Name. Powered by Just the Docs."

# Callouts (optional styling feature)
callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red
  tip:
    title: Tip
    color: green

# Theme as a remote theme for GitHub Pages
plugins:
  - jekyll-seo-tag
  - jekyll-feed
remote_theme: just-the-docs/just-the-docs
